config/routes.rb
Rails.application.routes.draw do
  root to: 'flats#index'

  resources :flats, only: [:show, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, :image_url, :price, :currency, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :image_url, :price, :currency)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class="container">
  <h1>All Flats</h1>

  <%= link_to "Add Flat", new_flat_path, class: 'btn btn-primary' %>

  <div class="flat-list">
    <% @flats.each do |flat| %>
      <div class="card-trip">
        <%= image_tag flat.image_url, width: "100%" %>
        <div class="card-trip-infos">
          <h2><%= flat.name %></h2>
          <h2 class="card-trip-pricing"><%= flat.currency %> <%= flat.price %></h2>
          <%= link_to "View", flat_path(flat), class: 'btn btn-dark' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container flat-form">
  <h1>Create a New Flat</h1>

  <%= simple_form_for @flat do |f| %>
    <%= f.input :name %>
    <%= f.input :image_url %>
    <%= f.input :price %>
    <%= f.input :currency, collection: ['CHF', 'EUR', 'USD'] %>
    <%= f.submit 'Add Flat', class: 'btn btn-success' %>
  <% end %>
</div>

app/views/flats/show.html.erb
<%= image_tag @flat.image_url %>

<div class="container">
  <h1><%= @flat.name %></h1>
  <p><%= @flat.currency %> <%= @flat.price %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>SimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>